"""add_processing_fields_to_document

Revision ID: 509dab74cbb5
Revises: d7b53d5c1c8f
Create Date: 2026-09-23 11:23:25.238748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '509dab74cbb5'
down_revision: Union[str, Sequence[str], None] = 'd7b53d5c1c8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('processing_status', sa.String(), server_default='uploaded', nullable=False))
    op.add_column('documents', sa.Column('extracted_text', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('processing_error', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'processed_at')
    op.drop_column('documents', 'processing_error')
    op.drop_column('documents', 'extracted_text')
    op.drop_column('documents', 'processing_status')
    # ### end Alembic commands ###
